### ISSUE TITLE
ctOP roadmap items

### ISSUE THREAD

**Issue by vijay-kota** [ctOP-IIITH/docs#2]
<h2>Design</h2>

- [x] Security between OM2M and subscription url
- [ ] Data privacy and security
   - Check if `bcrypt` hash for passwords is enough
   - Check for any sensitive data in the tables
- [x] Support statement for Mobius
- [ ] How does schema upgrade work?
- [ ] Is there enough logging to debug issues?
   - Do we know how to change logging levels to collect logs?
- [x] Do people in the team know how to build images (eg. compiling latest OM2M)
- [ ] Hosting of installation/deployment guide
- [ ] Hosting of development guide
- [ ] Do we have tests and how much is the coverage?
- [ ] What is the strategy for backup of registration data?
- [ ] What is the user flow for re-registration in case of compromised token?
<h2>Distribution</h2>

- [x] Will it be Docker images?
- [x] If Docker images, where will the images be downloaded from?
- [ ] For binary distribution, what are the LICENSE requirements?
- [x] Strategy for software upgrades
   - Versioning of software
<h2>Scale</h2>

- [ ] Look at resource requirements
- [ ] Decide Docker sizing (assuming Docker deployment)
- [x] Get perf numbers for number of requests that can be handled
<h2>City-level deployment</h2>

- [x] Get Wi-Sun limits for range
- [ ] Find a reference deployment
<h2>Ownership</h2>

- [ ] Will SCRC continue to maintain or open-source?

<h2>Check if these are bugs?</h2>

- [ ] In backend, `/get-node/{path}/latest` doesn't check for token. Why does this need to be allowed?
- [ ] In backend, `/subscribe` doesn't check for admin. Since subscriptions add to server overhead, should we check for admin access??
- [ ] In backend, why still have `/get-token` and `/deploy-token`
- [ ] In backend, why allow non-admin to do `/get-users`?
